apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: assisted-service-q2vh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: assisted-service-q2vh
    app.kubernetes.io/part-of: assisted-service
  name: assisted-service-q2vh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: assisted-service-q2vh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: assisted-service-q2vh
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/assisted-installer-tenant/assisted-service/assisted-service-q2vh@sha256:330ae9d1fad5a56a1386e4c126c6c8afb263e6e7e354798512031809e7251bc5
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
