apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: assisted-service-q2vh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: assisted-service-q2vh
    app.kubernetes.io/part-of: assisted-service
  name: assisted-service-q2vh
spec:
  selector:
    app.kubernetes.io/instance: assisted-service-q2vh
status:
  loadBalancer: {}
