apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: assisted-service-q2vh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/assisted-installer-tenant/assisted-service/assisted-service-q2vh@sha256:bbc6ddef2eeb1cadf0d2c1e633b18883e0aa33463621e29a212339b519a691d7
        name: my-python
        resources: {}
status: {}
