apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: assisted-service-q2vh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/assisted-installer-tenant/assisted-service/assisted-service-q2vh@sha256:411173c505f0a30943329a9c3d1d0ba7682c8c07a34355976f4d2a33c7fcc66b
        name: my-python
        resources: {}
status: {}
