apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: assisted-service-q2vh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/assisted-installer-tenant/assisted-service/assisted-service-q2vh@sha256:e0f229d612f55c17583c97e5c93e2dad9270e08d9a02e4149f268234dcf1dc55
        name: my-python
        resources: {}
status: {}
