apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: assisted-service-q2vh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/assisted-installer-tenant/assisted-service/assisted-service-q2vh@sha256:fc5a3569a4475c817a2cbd7aaada35d998ae6a2c1127e1deb1949600fda7facd
        name: my-python
        resources: {}
status: {}
